### ISSUE TITLE
Disable excessive debug logging by default

### ISSUE THREAD

**Issue by djcoleman** [release-engineering/offliner#23]
The offliner tool produces a large amount of debug output from the Apache HttpClient code - around 2000 lines for a POM file containing 1 dependency. This should be disabled by default.

**Comment by jdcasey** [comment]
@djcoleman So, would you say fixing the http-testserver dependency has fixed this issue?

**Comment by djcoleman** [comment]
Circumvented maybe, rather than fixed. But it sorted out the immediate problem I had with excessive debug, so I guess it can be closed.
