### ISSUE TITLE
Can't build offliner 1.3 

### ISSUE THREAD

**Issue by jonathanchristison** [release-engineering/offliner#32]
`[INFO] Maven-Manipulation-Extension 1.6
[main] INFO  o.c.m.ext.manip.ManipulationManager - Maven-Manipulation-Extension: No changes.
[main] INFO  o.c.m.ext.manip.ManipulationManager - Maven-Manipulation-Extension: Finished.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Offliner Maven Repository Downloader 1.3
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.commonjava.util:http-testserver:jar:1.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.747s
[INFO] Finished at: Wed Sep 21 10:50:08 BST 2016
[INFO] Final Memory: 13M/204M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project offliner: Could not resolve dependencies for project com.redhat.red.offliner:offliner:jar:1.3: Failure to find org.commonjava.util:http-testserver:jar:1.2 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

I had to clone and build https://github.com/Commonjava/http-testserver/blob/http-testserver-1.2 from source before i could do a successful build. Will this be deployed to central or will http-tesetserver need productising?

**Comment by jdcasey** [comment]
I had forgotten to close / release the staging repo for http-testserver, so it never got pushed to central. Fixed, and the artifacts should be on central in the next couple of hours.
