### ISSUE TITLE
Offliner documentation link broken

### ISSUE THREAD

**Issue by AntStephenson** [release-engineering/offliner#54]
The URL https://release-engineering.github.io/offliner/ does not work anymore. It is also mentioned in the README for this project.

Historic documentation has been broken by removing the original location for the offliner. I spotted references to it in the EAP and RHPAM/RHDM documentation.

**Comment by AntStephenson** [comment]
I found it exists at https://commonjava.github.io/offliner/, I'm not sure if its possible to reinstate the above the page and redirect, or at the very least put a notice on there for users.

**Comment by jcasey-rh** [comment]
Sorry, I didn't remember the docs. Would you mind filing a NOS issue and
assigning to me if you can? I'm out sick today...

John Casey
Principal Software Engineer
PnT DevOps (NOS team)
pronouns: he/him

**Comment by AntStephenson** [comment]
Done - NOS-2409

**Comment by jdcasey** [comment]
I moved the repo back to release-engineering org avoid lingering confusion.
